@startuml services_graph

    title Deployment Base Services Graph

    node "github.com" as github {
        database "Git Repository" as GitRepo [[https://github.com/imazzine/cli]]
        node "Git Server" as GitServer
        GitRepo <- GitServer: store
    }
    interface "Webhooks" as Webhooks [[https://developer.github.com/webhooks/]]
    interface "Rest API" as GitRestApi [[https://developer.github.com/v3/]]
    GitServer -- Webhooks
    GitServer -- GitRestApi
    
    node "npmjs.com" as npmjs {
        node "Npm Server" as NpmService
        database "Npm Package" as NpmPackage [[https://www.npmjs.com/package/@imazzine/cli]]
        NpmService -> NpmPackage: store
    }
    interface "Npm Interface" as NpmInterface [[https://docs.npmjs.com/]]
    NpmService -- NpmInterface

    node "travis-ci.com" as CICDServer {
        node "CI/CD Service" as CICDService [[https://travis-ci.com/imazzine/cli]]
    }
    interface "Travis API" as CICDInterface [[https://docs.travis-ci.com/user/languages/javascript-with-nodejs/]]
    CICDService -- CICDInterface
    Webhooks )-- CICDService
    GitRestApi )- CICDService
    CICDService --( NpmInterface
    
    node "Producer" as Producer {
        node "GIT Client" as GitClient [[https://git-scm.com/downloads]]
        interface "GIT CLI" as GitCli [[https://git-scm.com/book/en/v2/Getting-Started-The-Command-Line]]
        GitClient -- GitCli

        file "Source files" as Sources [[https://github.com/imazzine/cli]]
        file ".travis.yml" as CICDConf [[https://github.com/imazzine/cli/blob/master/.travis.yml]]
        file "package.json" as NPMConfig [[https://github.com/imazzine/cli/blob/master/package.json]]
        GitRepo "0..*" o-- Sources
        Sources *-- CICDConf
        Sources *-- NPMConfig
        GitRestApi )-- GitClient
        CICDInterface )-- CICDConf
        NpmInterface )-- NPMConfig
    }

    node "Consumer" as Consumer {
        node "NPM Client" as NPMClient [[https://www.npmjs.com/get-npm]]
        interface "NPM CLI" as BIN [[https://docs.npmjs.com/cli-documentation/]]
        NpmInterface )-- NPMClient
        NPMClient -- BIN

        file "Binaries" as Binaries
        interface "JS API" as API
        NpmPackage "0..*" o-- Binaries
        NPMClient -> Binaries: install
        Binaries -- API
    }
@enduml