@startuml
cloud "Internet/Intranet" {
    node "GIT\nserver" as gitServer {
        file "source \n code \n (.travis.yml, \n .gitlab-ci.yml)" as SourceCode
    }
    node "<b>CI/CD</b>\n<b>server</b>" as ciServer {
        node "Build Container (Docker)" as ciBuildNode
    }
    node "NPM\nserver" as npmServer  {
        package cli {
            file "server.js"
        }
        package plugins {
            file "cmd.js"
        }
    }
    interface "Webhooks + Bash + ..." as BashInterface

    SourceCode --( BashInterface
    BashInterface -- ciBuildNode
}
interface "GIT" as gitInterface
interface "NPM" as npmInterface

gitServer -- gitInterface
ciBuildNode --( gitInterface
npmServer -- npmInterface
ciBuildNode --( npmInterface

node "Leaders' Environment" as devPC {
    file "CLI Server \n sources"
    file "Plugins \n sources"
}
node "Developers' Environment" as userPC {
    component "NPM Client" as npmClient
    component "Node.js" as nodejs
    component "CLI Server" as CLIServer
    component "Plugable Command" as Plugin
    interface CLI
    nodejs <.. CLIServer: based on
    npmClient ..> CLIServer: use
    CLIServer .> Plugin: use
    npmClient - CLI
}
gitInterface )-- devPC
npmInterface )-- npmClient
@enduml